// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet():Promise<Record<string, string>>;

export function GetState():Promise<Record<string, any>>;

export function SavedAddress():Promise<string>;

export function StartMining(arg1:string,arg2:string):Promise<void>;

export function StopMining():Promise<void>;
