// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWallet() {
  return window['go']['main']['App']['CreateWallet']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function SavedAddress() {
  return window['go']['main']['App']['SavedAddress']();
}

export function StartMining(arg1, arg2) {
  return window['go']['main']['App']['StartMining'](arg1, arg2);
}

export function StopMining() {
  return window['go']['main']['App']['StopMining']();
}
